### PR TITLE
Nodejs week2

### PR DESCRIPTION
**Pull request by RodrigoGuinsbergPinto**

### CODE REVIEW

**Review by itsgauravsaxena — COMMENTED** [review]
Added

**Comment by RodrigoGuinsbergPinto** [comment]
Hi Gaurav,
thank you for the comment, but what do you mean by 'added'?

**Comment by itsgauravsaxena** [comment]
Sorry it seems like a mistake.

**Review by itsgauravsaxena — APPROVED** [review]

**Comment by RodrigoGuinsbergPinto** [comment]
Oh, ok.
Thank you for the review.

**Pull request merged**
